name: Testing
on: push 
# Indica que cada vez que archivos se mandan al repository
# PUSH: Se ejecuta el test

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install django
        python3 manage.py test